### ISSUE TITLE
ANR on Android 11-12 in Samsung devices. 

### ISSUE THREAD

**Issue by mjagad1196** [BlinkReceipt/blinkreceipt-android#45]
Hi Team,

During init of the camera to scan the receipts, when the camera is opened for too long or after opening the camera keeping the app in background, ANR occurs for Samsung devices which runs on Android 11 and Android 12. Attaching ANR log form firebase crashlytics. 

Stacktrace Text:

main (native): tid=1 systid=395 
#00 pc 0xd7758 libc.so (sched_setaffinity + 8)
#01 pc 0x7dace4 split_config.arm64_v8a.apk!libBlinkReceipt.so 
       at java.lang.Runtime.nativeLoad(Runtime.java)
       at java.lang.Runtime.nativeLoad(Runtime.java:1131)
       at java.lang.Runtime.loadLibrary0(Runtime.java:1085)
       at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
       at java.lang.System.loadLibrary(System.java:1664)
       at com.microblink.internal.NativeLibraryLoader.loadNativeLibrary(NativeLibraryLoader.java)
       at com.microblink.BlinkReceiptSdk.<clinit>(BlinkReceiptSdk.java)
       at com.microblink.BlinkRecognizerProvider.onCreate(BlinkRecognizerProvider.java)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2429)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2399)
       at android.app.ActivityThread.installProvider(ActivityThread.java:8107)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:7643)
       at android.app.ActivityThread.handleMakeApplication(ActivityThread.java:7527)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7484)
       at android.app.ActivityThread.access$1400(ActivityThread.java:301)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2156)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8550)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
       
       
       
       Stacktrace Data:
       
       com.microblink.internal.NativeLibraryLoader.loadNativeLibrary (NativeLibraryLoader.java)
       com.microblink.BlinkReceiptSdk.<clinit> (BlinkReceiptSdk.java)
       com.microblink.BlinkRecognizerProvider.onCreate (BlinkRecognizerProvider.java)

**Comment by pequots34** [comment]
This is an OS issue specific to that version. It was patched by Google but was not required to be taken by the OEM. Can you please share a project reproducing the issue so we can debug it to be sure it's the same issue reported by Google?

Thanks
