### ISSUE TITLE
Demo App Crashes When Opening The Camera Activity

### ISSUE THREAD

**Issue by cdflynn** [BlinkReceipt/blinkreceipt-android#5]
Here's the complete contents of Logcat where the following two steps are performed:

1. Start the `BlinkReceiptCustomScan` application (You will see `MainActivity` with the camera button in the toolbar, top right)
2. Tap the camera button in the toolbar

Observe:

```
2018-10-05 09:53:22.951 9600-9600/com.blinkreceipt.ocr D/OpenGLRenderer: Skia GL Pipeline
2018-10-05 09:53:23.001 9600-9680/com.blinkreceipt.ocr I/Adreno: QUALCOMM build                   : 984b9a6, Ibe1bf21abc
    Build Date                       : 06/04/18
    OpenGL ES Shader Compiler Version: EV031.24.00.00
    Local Branch                     : googldrp
    Remote Branch                    : 
    Remote Branch                    : 
    Reconstruct Branch               : 
2018-10-05 09:53:23.001 9600-9680/com.blinkreceipt.ocr I/Adreno: Build Config                     : S L 4.0.10 AArch64
2018-10-05 09:53:23.009 9600-9680/com.blinkreceipt.ocr I/Adreno: PFP: 0x005ff110, ME: 0x005ff066
2018-10-05 09:53:23.013 9600-9680/com.blinkreceipt.ocr I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
2018-10-05 09:53:23.013 9600-9680/com.blinkreceipt.ocr I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2018-10-05 09:53:23.014 9600-9680/com.blinkreceipt.ocr I/OpenGLRenderer: Initialized EGL, version 1.4
2018-10-05 09:53:23.014 9600-9680/com.blinkreceipt.ocr D/OpenGLRenderer: Swap behavior 1
2018-10-05 09:53:41.188 9600-9600/com.blinkreceipt.ocr W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@8e73f4a
2018-10-05 09:53:41.373 9600-9600/com.blinkreceipt.ocr W/RecognizerView.java:82@main: CameraView is already disposed. Cannot set metering areas!
2018-10-05 09:53:41.377 9600-9600/com.blinkreceipt.ocr D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
2018-10-05 09:53:41.379 9600-9600/com.blinkreceipt.ocr E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.blinkreceipt.ocr, PID: 9600
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.blinkreceipt.ocr/com.blinkreceipt.ocr.ui.CameraActivity}: SdkNotInitializedException{, isNativeLibraryLoaded=false, nativeError=null}
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: SdkNotInitializedException{, isNativeLibraryLoaded=false, nativeError=null}
        at com.microblink.internal.Validate.sdkInitialized(Unknown Source:24)
        at com.microblink.RecognizerView.initialize(Unknown Source:19)
        at com.blinkreceipt.ocr.ui.CameraActivity.onCreate(CameraActivity.java:122)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2018-10-05 09:53:41.390 9600-9600/com.blinkreceipt.ocr I/Process: Sending signal. PID: 9600 SIG: 9
```

Note that there is a license key already declared in the `AndroidManifest` of the demo application:
https://github.com/BlinkReceipt/blinkreceipt-android/blob/553641df151d29bac0b2700313a0b77362621254/BlinkReceiptDemo/BlinkReceiptExtensions/src/main/AndroidManifest.xml#L12

**Comment by pequots34** [comment]
The license key is invalid. The demo is to show how to integrate within your own application.
