### ISSUE TITLE
SdkNotInitializedException

### ISSUE THREAD

**Issue by Vikashhalwai** [BlinkReceipt/blinkreceipt-android#6]
2018-10-10 11:27:00.021 2386-2386/ocr.blinkreceipt.com.demoocrapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ocr.blinkreceipt.com.demoocrapp, PID: 2386
    java.lang.RuntimeException: Unable to start activity ComponentInfo{ocr.blinkreceipt.com.demoocrapp/com.microblink.CameraScanActivity}: SdkNotInitializedException{, isNativeLibraryLoaded=false, nativeError=null}
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: SdkNotInitializedException{, isNativeLibraryLoaded=false, nativeError=null}
        at com.microblink.internal.Validate.sdkInitialized(Unknown Source:11)
        at com.microblink.RecognizerView.initialize(Unknown Source:0)
        at com.microblink.CameraScanActivity.onCreate(Unknown Source:623)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by Vikashhalwai** [comment]
When I am Starting CameraActivity getting above issue, please suggest.

**Comment by ntsparis** [comment]
Try to add this code in **onCreate**:

ReceiptSdk.sdkInitialize(this, "GET_CODE", new InitializeCallback() {
            @Override
            public void onInitialized() {
                Log.i("test","InitializedDone");
            }
            @Override
            public void onException(@NonNull ReceiptSdkException e) {
                Log.i("test",e.toString());
            }
        });

**Comment by pequots34** [comment]
Please make sure you have valid license key to unlock the SDK. Also, please check out the demo projects.
